const ExamActionTypes = {
  FETCH_FULL_EXAM_START: 'FETCH_FULL_EXAM_START',
  FETCH_EXAMS_LIST_START: 'FETCH_EXAMS_LIST_START',
  FETCH_EXAMS_LIST_SUCCESS: 'FETCH_EXAMS_LIST_SUCCESS',
  FETCH_EXAMS_LIST_FAILURE: 'FETCH_EXAMS_LIST_FAILURE'
}

export default ExamActionTypes;