const LessonActionTypes = {
  FETCH_FULL_LESSON_START: 'FETCH_FULL_LESSON_START',
  FETCH_LESSON_LIST_START: 'FETCH_LESSON_LIST_START',
  FETCH_LESSON_LIST_SUCCESS: 'FETCH_LESSON_LIST_SUCCESS',
  FETCH_LESSON_LIST_FAILURE: 'FETCH_LESSON_LIST_FAILURE'
}

export default LessonActionTypes;